
package tugas.uts;


public class uts1 extends javax.swing.JFrame {

    String nama="",jk,asal="",nomortelepon="";
    public uts1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isinama = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pilihlk = new javax.swing.JRadioButton();
        pilihpr = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        isiasal = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        isinotelp = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        isiemail = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        batal = new javax.swing.JButton();
        lanjut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1020, 550));
        setSize(new java.awt.Dimension(940, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isinama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isinama.setBorder(null);
        isinama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isinamaActionPerformed(evt);
            }
        });
        getContentPane().add(isinama, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 400, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 390, 10));

        pilihlk.setBackground(new java.awt.Color(255, 255, 255));
        pilihlk.setText("Laki-laki");
        pilihlk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihlkActionPerformed(evt);
            }
        });
        getContentPane().add(pilihlk, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 100, -1));

        pilihpr.setBackground(new java.awt.Color(255, 255, 255));
        pilihpr.setText("Perempuan");
        pilihpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihprActionPerformed(evt);
            }
        });
        getContentPane().add(pilihpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 100, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 380, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 390, 10));

        isiasal.setBorder(null);
        getContentPane().add(isiasal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 380, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 390, 20));

        isinotelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isinotelp.setBorder(null);
        getContentPane().add(isinotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 240, 30));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 240, 10));

        isiemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isiemail.setBorder(null);
        isiemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiemailActionPerformed(evt);
            }
        });
        getContentPane().add(isiemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 240, 30));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 240, 10));

        batal.setBackground(new java.awt.Color(255, 255, 255));
        batal.setIcon(new javax.swing.ImageIcon("D:\\INTERAKSI MANUSIA KOMPUTER\\logintespute\\src\\image\\BATAL.png")); // NOI18N
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 110, 30));

        lanjut.setIcon(new javax.swing.ImageIcon("D:\\INTERAKSI MANUSIA KOMPUTER\\logintespute\\src\\image\\lanjut.png")); // NOI18N
        lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutActionPerformed(evt);
            }
        });
        getContentPane().add(lanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bio2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1020, 550));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isinamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isinamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isinamaActionPerformed

    private void pilihprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihprActionPerformed

    private void pilihlkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihlkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihlkActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_batalActionPerformed

    private void lanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutActionPerformed
        // TODO add your handling code here:
        menu muncul= new menu();
        dispose();
        
        
        nama = isinama.getText();
        isinama.setText("");
        
        
        if(pilihlk.isSelected())
            jk = pilihlk.getText();
        else
            jk = pilihpr.getText();
        
        
        new menu().setVisible(true);
    }//GEN-LAST:event_lanjutActionPerformed

    private void isiemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uts1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uts1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uts1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uts1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uts1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JTextField isiasal;
    private javax.swing.JTextField isiemail;
    private javax.swing.JTextField isinama;
    private javax.swing.JTextField isinotelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton lanjut;
    private javax.swing.JRadioButton pilihlk;
    private javax.swing.JRadioButton pilihpr;
    // End of variables declaration//GEN-END:variables
}
